// Stricter than the browser's type="email", rejects single-char TLDs,
// IP literals, quoted strings, and other technically-valid-but-never-real forms.
const FORMAT_REGEX =
  /^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9](?:[a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$/;

// Keyboard-walk patterns that appear frequently in fake signups.
const KEYBOARD_WALKS = [
  'qwerty', 'qwertz', 'azerty', 'asdfgh', 'zxcvbn',
  'abcdef', 'abcdefg', '123456', '12345678', '1234567',
  'qweasd', 'zxcasd',
];

// Top abused disposable / throwaway email providers.
// Sourced from disposable-email-domains open dataset, curated to highest-traffic domains.
const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com', 'mailinator2.com', 'mailinator.net',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.info', 'guerrillamail.de',
  'guerrillamailblock.com', 'grr.la', 'spam4.me',
  'sharklasers.com', 'guerrillamail.info',
  'tempmail.com', 'tempmail.net', 'temp-mail.org', 'temp-mail.io',
  'tempr.email', 'temp.email', 'tempinbox.com',
  '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minutemail.co.uk',
  'throwam.com', 'throwaway.email', 'throw.email',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'cool.fr.nf', 'jetable.fr.nf', 'nospam.ze.tc',
  'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr',
  'courriel.fr.nf', 'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spambox.us', 'spam4.me', 'spamhereplease.com', 'spamthisplease.com', 'spamevader.net',
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'trashmail.at', 'trashmail.io', 'trashmail.xyz', 'trash-mail.com',
  'mailnull.com', 'mailnesia.com', 'maildrop.cc',
  'dispostable.com', 'discard.email',
  'fakeinbox.com', 'fakeinbox.net', 'fakeinbox.org',
  'notsharingmy.info',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'crap.la', 'crapmail.org',
  'getairmail.com', 'filzmail.com', 'getnada.com',
  'mailtemp.net', 'tempinbox.co.uk',
  'bobmail.info', 'bofthew.com',
  'byom.de', 'chammy.info',
  'chogmail.com', 'clrmail.com', 'cmail.club',
  'cosmorph.com', 'curryworld.de', 'dacoolest.com',
  'deadaddress.com', 'deadletter.ga',
  'despam.it', 'dfgh.net',
  'digitalsanctuary.com', 'dingbone.com',
  'discardmail.com', 'discardmail.de',
  'dodgit.com', 'donemail.ru',
  'dontreg.com', 'dontsendmespam.de',
  'drdrb.net', 'dump-email.info',
  'dumpandfuck.com', 'dumpmail.de',
  'dumpyemail.com', 'e4ward.com',
  'email60.com', 'emailias.com',
  'emailinfive.com', 'emailmiser.com',
  'emailsensei.com', 'emailtemporanea.com',
  'emailtemporanea.net', 'emailtemporar.ro',
  'emailto.de', 'emailwarden.com',
  'emz.net', 'enterto.com',
  'ephemail.net', 'explodemail.com',
  'fakemailgenerator.com', 'fakemail.fr',
  'filzmail.com', 'fishide.com',
  'fizmail.com', 'fleckens.hu',
  'frapmail.com', 'front14.org',
  'fuckingduh.com', 'fudgerub.com',
  'garliclife.com', 'get1mail.com',
  'get2mail.fr', 'getamailbox.org',
  'getonemail.com', 'getonemail.net',
  'girlsundertheinfluence.com', 'gishpuppy.com',
  'gowikibooks.com', 'gowikicampus.com',
  'greensloth.com', 'gsrv.co.uk',
  'gustr.com', 'gynzi.com',
  'h.mintemail.com', 'h8s.org',
  'haltospam.com', 'hatespam.org',
  'hidemail.de', 'hidzz.com',
  'hmamail.com', 'hopemail.biz',
  'hulapla.de', 'ieatspam.eu',
  'ieatspam.info', 'ieh-mail.de',
  'ihateyoualot.info', 'iheartspam.org',
  'imails.info', 'inbax.tk',
  'inboxclean.com', 'inboxclean.org',
  'inoutmail.de', 'inoutmail.eu',
  'inoutmail.info', 'inoutmail.net',
  'internet-v-moldova.com', 'internetemails.net',
  'ipsur.org', 'irish2me.com',
  'iwi.net', 'jetable.com',
  'jetable.fr.nf', 'jetable.net',
  'jetable.org', 'jnxjn.com',
  'jourrapide.com', 'jsrsolutions.com',
  'junk.to', 'junkmail.ga',
  'junkmail.gq', 'jupimail.com',
  'kasmail.com', 'keepmymail.com',
  'killmail.com', 'killmail.net',
  'kir.ch.tc', 'klassmaster.com',
  'klzlk.com', 'koszmail.pl',
  'kurzepost.de', 'lawlita.com',
  'letthemeatspam.com', 'lhsdv.com',
  'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'lol.ovpn.to',
  'lookugly.com', 'lortemail.dk',
  'lr78.com', 'lroid.com',
  'lukop.dk', 'm21.cc',
  'mail-filter.com', 'mail-temporaire.fr',
  'mail.by', 'mail.mezimages.net',
  'mail.zp.ua', 'mail1a.de',
  'mail2rss.org', 'mail333.com',
  'mailbidon.com', 'mailbiz.biz',
  'mailblocks.com', 'mailbucket.org',
  'mailcat.biz', 'mailcatch.com',
  'mailde.de', 'mailde.info',
  'maildrop.cc', 'maileimer.de',
  'mailexpire.com', 'mailfa.tk',
  'mailforspam.com', 'mailfreeonline.com',
  'mailguard.me', 'mailimate.com',
  'mailin8r.com', 'mailinatar.com',
  'mailismagic.com', 'mailme.lv',
  'mailme24.com', 'mailmetrash.com',
  'mailmoat.com', 'mailms.com',
  'mailnew.com', 'mailnull.com',
  'mailpick.biz', 'mailproxsy.com',
  'mailquack.com', 'mailrock.biz',
  'mailsac.com', 'mailscrap.com',
  'mailshell.com', 'mailsiphon.com',
  'mailslapping.com', 'mailslite.com',
  'mailsnull.com', 'mailspam.me',
  'mailspam.xyz', 'mailstemporary.com',
  'mailtome.de', 'mailtothis.com',
  'mailtrash.net', 'mailtv.net',
  'mailtv.tv', 'mailwithyou.com',
  'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'malahov.de',
  'manifestgenerator.com', 'manybrain.com',
  'mb69.com', 'mbx.cc',
  'mega.zik.dj', 'meinspamschutz.de',
  'meltmail.com', 'messagebeamer.de',
  'mezimages.net', 'mfsa.ru',
  'mierdamail.com', 'migmail.pl',
  'migumail.com', 'mindless.com',
  'mintemail.com', 'misterpinball.de',
  'mjukglass.nu', 'moakt.com',
  'moaktmail.com', 'mobi.web.id',
  'mockmyid.com', 'moncourrier.fr.nf',
  'monkeypox.co.uk', 'mopmail.com',
  'mox.pp.ua', 'mperial.de',
  'msa.minsmail.com', 'mt2009.com',
  'mt2014.com', 'mt2015.com',
  'mucincanon.com', 'munzdesign.de',
  'mwork.com', 'mx0.wwwnew.eu',
  'my10minutemail.com', 'myalias.pw',
  'mymail-in.net', 'mymailoasis.com',
  'mynetstore.de', 'myphantomemail.com',
  'mysamp.de', 'myspamless.com',
  'mytempemail.com', 'mytempmail.com',
  'mytrashmail.com', 'neomailbox.com',
  'nepwk.com', 'nervmich.net',
  'nervtmich.net', 'netmails.com',
  'netmails.net', 'netzidiot.de',
  'neverbox.com', 'nice-4u.com',
  'nincsmail.hu', 'nnh.com',
  'no-spam.ws', 'nobulk.com',
  'noclickemail.com', 'nomail2me.com',
  'nomorespamemails.com', 'nonspam.eu',
  'nonspammer.de', 'nospam.ze.tc',
  'nospam4.us', 'nospamfor.us',
  'nospammail.net', 'notmailinator.com',
  'nowmymail.com', 'nus.edu.sg',
  'nwldx.com', 'objectmail.com',
  'obobbo.com', 'odaymail.com',
  'odnorazovoe.ru', 'oneoffemail.com',
  'onewaymail.com', 'online.ms',
  'onqin.com', 'oopi.org',
  'opayq.com', 'opentrash.com',
  'ordinaryamerican.net', 'otisweb.com',
  'our.st', 'ourklips.com',
  'outlawspam.com', 'ovpn.to',
  'owlpic.com', 'pancakemail.com',
  'paplease.com', 'pecinan.com',
  'pecinan.net', 'pecinan.org',
  'pepbot.com', 'peterdethier.com',
  'petml.com', 'pfui.ru',
  'phishing-warning.fake', 'pimpedupmyride.com',
  'pingir.com', 'pisosmail.com',
  'planetmail.com', 'planetmail.net',
  'plexolan.de', 'poczta.onet.pl',
  'pookmail.com', 'postalmail.biz',
  'ppetw.com', 'privacy.net',
  'privatdemail.net', 'proxymail.eu',
  'prtnx.com', 'prtz.eu',
  'punkass.com', 'putthisinyourspamdatabase.com',
  'pwrby.com', 'qq.com',
  'r4nd0m.de', 'raetp9.com',
  'raketenmann.de', 'rancidhome.net',
  'rar.ro', 'razordevil.com',
  'rcpt.at', 're-gister.com',
  'recursor.net', 'reddcoin.com',
  'recyclemail.dk', 'rejectmail.com',
  'reliable-mail.com', 'relic-today.com',
  'remailer.com', 'remailtrap.com',
  'renraku.in', 'rhyta.com',
  'rklips.com', 'rmqkr.net',
  'robot-mail.com', 'roon.io',
  'rostemail.com', 'rppkn.com',
  'rtrtr.com', 'ru.ru',
  's0ny.net', 'safe-mail.ga',
  'safemail.ml', 'safetymail.info',
  'safetypost.de', 'sandelf.de',
  'saynotospams.com', 'schafsmail.com',
  'schafmail.de', 'selfdestructingmail.com',
  'sendspamhere.com', 'senseless-entertainment.com',
  'services391.com', 'sharedmailbox.org',
  'shieldedmail.com', 'shieldemail.com',
  'shiftmail.com', 'shitmail.me',
  'shitmail.org', 'shitware.nl',
  'shmeriously.com', 'shortmail.net',
  'sibmail.com', 'silentmail.org',
  'sinnlos-mail.de', 'siteposter.net',
  'skeefmail.com', 'slapsfromlastnight.com',
  'slaskpost.se', 'slave-auctions.net',
  'slippery.email', 'slopsbox.com',
  'slushmail.com', 'smellfear.com',
  'smellrear.com', 'snakemail.com',
  'sneakemail.com', 'sneakmail.de',
  'snkmail.com', 'sofimail.com',
  'sofort-mail.de', 'sogetthis.com',
  'soisz.com', 'solar-impact.pro',
  'solopilotsjourney.com', 'soodonims.com',
  'spam.la', 'spam.mn',
  'spam.su', 'spamavert.com',
  'spambo.net', 'spambob.net',
  'spambob.org', 'spambog.com',
  'spambog.de', 'spambog.ru',
  'spambouncr.com', 'spamcannon.com',
  'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com',
  'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com',
  'spamdecoy.net', 'spamex.com',
  'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgoes.in',
  'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'spamherelots.com',
  'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info',
  'spaml.de', 'spaml.com',
  'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spampaste.com',
  'spamspot.com', 'spamstack.net',
  'spamthisplease.com', 'spamtrap.ro',
  'spamtroll.net', 'speedymail.org',
  'splyff.in', 'spocmail.com',
  'spray.se', 'srekcah.org',
  'ssl.tls.cloudns.asia',
  'sssss.ml', 'stinkefinger.net',
  'stop-my-spam.com', 'streetwisemail.com',
  'suburbanthug.com', 'supergreatmail.com',
  'supermailer.jp', 'superstachel.de',
  'suremail.info', 'svip520.cn',
  'sweetxxx.de', 'tafmail.com',
  'tagyourself.com', 'techemail.com',
  'techgroup.me', 'teewars.org',
  'telecomix.pl', 'teleworm.com',
  'teleworm.us', 'temp-mail.de',
  'tempail.com', 'tempalias.com',
  'tempe-mail.com', 'tempemail.biz',
  'tempemail.co.za', 'tempemail.com',
  'tempemail.net', 'tempimbox.com',
  'tempmail.de', 'tempmail.eu',
  'tempmail.it', 'tempmail2.com',
  'tempmailer.com', 'tempmailer.de',
  'tempomail.fr', 'temporarioemail.com.br',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com', 'temporaryinbox.com',
  'temporarymailaddress.com', 'tempsky.com',
  'tempthe.net', 'tempymail.com',
  'thanksnospam.info', 'thankyou2010.com',
  'thc.st', 'thecloudindex.com',
  'thelimestones.com', 'thisisnotmyrealemail.com',
  'thismail.net', 'thrashmail.com',
  'throwam.com', 'throwam.net',
  'tinoza.org', 'tittbit.in',
  'tmail.com', 'tmailinator.com',
  'toiea.com', 'tokenmail.de',
  'top1post.ru', 'topranklist.de',
  'torchmail.com', 'tradermail.info',
  'trash-mail.com', 'trash-me.com',
  'trash2009.com', 'trash2010.com',
  'trash2011.com', 'trashdevil.com',
  'trashdevil.de', 'trashemail.de',
  'trashimail.com', 'trashmail.app',
  'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.io',
  'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.xyz',
  'trashmailer.com', 'trashme.com',
  'trashmymail.com', 'trbvm.com',
  'trbvn.com', 'trillianpro.com',
  'trollmail.de', 'tryalert.com',
  'turual.com', 'twinmail.de',
  'twoweirdtricks.com', 'tyldd.com',
  'ubismail.net', 'uggsrock.com',
  'umail.net', 'unode.net',
  'unseen.is', 'upliftnow.com',
  'uroid.com', 'us.af',
  'used.black', 'used.blue',
  'used.nu', 'user.outofbrain.com',
  'uzxia.cc', 'valemail.net',
  'venompen.com', 'veryrealemail.com',
  'vidchart.com', 'viditag.com',
  'viewcastmedia.net', 'viewcastmedia.org',
  'viralplays.com', 'vkcode.ru',
  'vomoto.com', 'vpn.st',
  'vspence.com', 'w3internet.co.uk',
  'walala.org', 'walkmail.net',
  'walkmail.ru', 'wam.co.za',
  'wastemail.com', 'webemail.me',
  'webm4il.info', 'webuser.in',
  'wee.my', 'wefjo.granda.es',
  'weg-werf-email.de', 'wegwerf-emails.de',
  'wegwerfadresse.de', 'wegwerfmail.de',
  'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org', 'wetrainbayarea.org',
  'wh4f.org', 'whopy.com',
  'wicked-game.co.uk', 'wickedmail.com',
  'wilemail.com', 'willhackforfood.biz',
  'willselfdestruct.com', 'winemaven.info',
  'wmail.cf', 'wolfmail.ml',
  'wollan.info', 'worldpsy.com',
  'wuzupmail.net', 'www.com',
  'www.e4ward.com', 'www.mailinator.com',
  'wwwnew.eu', 'wyvernia.net',
  'x.ip6.li', 'xagloo.com',
  'xemaps.com', 'xents.com',
  'xmail.io', 'xmaily.com',
  'xn--9kq967o.com', 'xoxox.cc',
  'xwaretech.com', 'xwaretech.info',
  'xwaretech.net', 'xww.ro',
  'xxolocal.com', 'xyz.am',
  'yapped.net', 'yeah.net',
  'yep.it', 'yogamaven.com',
  'yomail.info', 'yopmail.com',
  'yopmail.fr', 'yopmail.pp.ua',
  'youmail.ga', 'youmailr.com',
  'yourspamgoeshere.com', 'ypmail.webarnak.fr.eu.org',
  'yuurok.com', 'z1p.biz',
  'za.com', 'zebins.com',
  'zebins.eu', 'zehnminutenmail.de',
  'zetmail.com', 'zippymail.in',
  'zoaxe.com', 'zoemail.com',
  'zoemail.net', 'zoemail.org',
  'zomg.info', 'zxcvbnm.com',
]);

export type EmailValidationReason = 'format' | 'disposable' | 'suspicious';

export type EmailValidationResult =
  | { valid: true; normalised: string }
  | { valid: false; reason: EmailValidationReason };

function isSuspiciousLocalPart(local: string): boolean {
  // All identical characters (e.g. "aaaa", "1111")
  if (local.length > 1 && local.split('').every((c) => c === local[0])) return true;

  // Keyboard walks
  const l = local.toLowerCase();
  for (const walk of KEYBOARD_WALKS) {
    if (l.includes(walk)) return true;
  }

  return false;
}

/**
 * Validates an email address on format, disposable domain, and suspicious patterns.
 * Safe to call from both client and server, no Node.js APIs used here.
 */
export function validateEmail(raw: string): EmailValidationResult {
  const normalised = raw.trim().toLowerCase();

  if (!FORMAT_REGEX.test(normalised)) {
    return { valid: false, reason: 'format' };
  }

  const [local, domain] = normalised.split('@');

  if (DISPOSABLE_DOMAINS.has(domain)) {
    return { valid: false, reason: 'disposable' };
  }

  if (isSuspiciousLocalPart(local)) {
    return { valid: false, reason: 'suspicious' };
  }

  return { valid: true, normalised };
}

// User-facing strings deliberately do NOT live here anymore. validateEmail()
// returns a typed `reason` code; WaitlistForm maps it to a localized message
// via t(`waitlist.errors.${reason}`). See SPEC-i18n §6.
